PRAGMA foreign_keys = ON;

-- STUDENT
CREATE TABLE Student (
    StudentID INTEGER PRIMARY KEY AUTOINCREMENT,
    Namn TEXT NOT NULL,
    Personnummer INTEGER NOT NULL,
    Årskull INTEGER NOT NULL
);

-- STUDENTINLOGGNING
CREATE TABLE Studentinloggning (
    StudentID INTEGER PRIMARY KEY,
    Lösenord TEXT NOT NULL,
    FOREIGN KEY (StudentID) REFERENCES Student(StudentID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

-- KURS
CREATE TABLE Kurs (
    KursID INTEGER PRIMARY KEY AUTOINCREMENT,
    Namn TEXT NOT NULL,
    Studietakt REAL NOT NULL,
    Ort TEXT NOT NULL,
    Studieplatser INTEGER NOT NULL,
    Kurskod TEXT NOT NULL,
    Högskolepoäng REAL NOT NULL
);

-- KURSTILLFÄLLE
CREATE TABLE Kurstillfälle (
    KurstillfälleID TEXT PRIMARY KEY,
    KursID INTEGER NOT NULL,
    Datum TEXT NOT NULL,
    FOREIGN KEY (KursID) REFERENCES Kurs(KursID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

-- BETYG
CREATE TABLE Betyg (
    BetygID INTEGER PRIMARY KEY AUTOINCREMENT,
    StudentID INTEGER NOT NULL,
    MomentID INTEGER,
    Värde TEXT NOT NULL,
    FOREIGN KEY (StudentID) REFERENCES Student(StudentID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

-- MOMENT
CREATE TABLE Moment (
    MomentID INTEGER PRIMARY KEY AUTOINCREMENT,
    KurstillfälleID TEXT NOT NULL,
    BetygID INTEGER,
    FOREIGN KEY (KurstillfälleID) REFERENCES Kurstillfälle(KurstillfälleID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (BetygID) REFERENCES Betyg(BetygID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

-- REGISTRERING
CREATE TABLE Registrering (
    StudentID INTEGER NOT NULL,
    KurstillfälleID TEXT NOT NULL,
    PRIMARY KEY (StudentID, KurstillfälleID),
    FOREIGN KEY (StudentID) REFERENCES Student(StudentID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (KurstillfälleID) REFERENCES Kurstillfälle(KurstillfälleID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

-- LÄRARE
CREATE TABLE Lärare (
    LärareID INTEGER PRIMARY KEY AUTOINCREMENT,
    Namn TEXT NOT NULL,
    Personnummer INTEGER NOT NULL,
    KurstillfälleID TEXT NOT NULL,
    FOREIGN KEY (KurstillfälleID) REFERENCES Kurstillfälle(KurstillfälleID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

-- ADMIN
CREATE TABLE Admin (
    AdminID INTEGER PRIMARY KEY AUTOINCREMENT,
    Namn TEXT NOT NULL,
    Epost TEXT NOT NULL,
    Roll TEXT NOT NULL
);

-- RAPPORTERING
CREATE TABLE Rapportering (
    RapporteringID INTEGER PRIMARY KEY AUTOINCREMENT,
    StudentID INTEGER NOT NULL,
    MomentID INTEGER NOT NULL,
    KurstillfälleID TEXT NOT NULL,
    LärareID INTEGER NOT NULL,
    AdminID INTEGER NOT NULL,
    FOREIGN KEY (StudentID) REFERENCES Student(StudentID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (MomentID) REFERENCES Moment(MomentID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (KurstillfälleID) REFERENCES Kurstillfälle(KurstillfälleID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (LärareID) REFERENCES Lärare(LärareID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (AdminID) REFERENCES Admin(AdminID)
        ON DELETE CASCADE ON UPDATE CASCADE
);
